### ISSUE TITLE
Fixing Dark Mode Feature

### ISSUE THREAD

**Issue by uchiha-vivek** [hooman96/momento#12]
![Screenshot (4)](https://github.com/hooman96/momento/assets/149925316/3a512350-69f0-47b2-8f0e-24acadba4a6d)

![Screenshot (5)](https://github.com/hooman96/momento/assets/149925316/cd6f8593-2477-4172-95bf-163c068bceaf)

The purpose is to make the text visible in dark mode.

File route -->momento-->src-->screens-->blog-->index.js

**Comment by hooman96** [comment]
move these under UI components
